/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__pytopojson__to_geojson__transform
#define __PYX_HAVE__pytopojson__to_geojson__transform

struct Point;
typedef struct Point Point;
struct Trans_param;
typedef struct Trans_param Trans_param;
struct Scale_param;
typedef struct Scale_param Scale_param;

/* "pytopojson/to_geojson/transform.pyx":2
 * # -*- coding: utf-8 -*-
 * ctypedef public struct Point:             # <<<<<<<<<<<<<<
 *     double x
 *     double y
 */
struct Point {
  double x;
  double y;
};

/* "pytopojson/to_geojson/transform.pyx":6
 *     double y
 * 
 * ctypedef public struct Trans_param:             # <<<<<<<<<<<<<<
 *     double x
 *     double y
 */
struct Trans_param {
  double x;
  double y;
};

/* "pytopojson/to_geojson/transform.pyx":10
 *     double y
 * 
 * ctypedef public struct Scale_param:             # <<<<<<<<<<<<<<
 *     double x
 *     double y
 */
struct Scale_param {
  double x;
  double y;
};

#ifndef __PYX_HAVE_API__pytopojson__to_geojson__transform

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__pytopojson__to_geojson__transform */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittransform(void);
#else
PyMODINIT_FUNC PyInit_transform(void);
#endif

#endif /* !__PYX_HAVE__pytopojson__to_geojson__transform */
